### ISSUE TITLE
"compatibility" with `xclip`

### ISSUE THREAD

**Issue by farzadmf** [aymanbagabas/shcopy#1]
Hey,

First of all, great tool. Just installed and it works perfectly.

I had a request. I completely understand if it's too specific for my use case, but I thought it's worth asking:

When using the tool directly, there's no problem whatsoever, and I can create my own aliases to point to `shcopy`. However, for apps and tools relying on the underlying binaries, there will be issues.

For example, I'm using lazygit SUPER extensively, and to make its copy functionality work, I've symlinked `xclip` (which is used by [atotto/clipboard](https://github.com/atotto/clipboard) to do the copying) to a script I have.

And my script basically "ignores" the flags passed to `xclip` (in the case of [copying](https://github.com/atotto/clipboard/blob/master/clipboard_unix.go#L37), it's something like `xclip -in -selection clipboard`

I was wondering if there's the possiblity of doing that in your tool so that I can get rid of my custom script for good and start using `shcopy` everywhere.

As I said, I totally understand if you think the use case is too specific

**Comment by aymanbagabas** [comment]
Hi @farzadmf

Afaik, since this is related to lazygit, I don't think there is much `shcopy` can do. You could try opening a new lazygit issue to support ANSI OSC52 using [go-osc52](https://github.com/aymanbagabas/go-osc52) perhaps.

**Comment by farzadmf** [comment]
Hey @aymanbagabas , thank you for your reply. What you said makes sense.

Just wondering, does `go-osc52` also work with terminals that don't support it? I guess that would be very rare nowadays for a terminal not to support them, but just in case that happens.

Also, the "issue" I mentioned is not necessarily `lazygit`-specfic, but every Go app that uses the [atotto/clipboard](https://github.com/atotto/clipboard) package to do the copying.
